### ISSUE TITLE
Character encoding on the .csv export

### ISSUE THREAD

**Issue by andpiazza** [frdmn/rocketchat-export-userlist#2]
Character encoding for the field "Names" on the CSV file is not fully resolved.

Examples:
PÃ¢mela => Pâmela
SÃ´nia => Sônia
JÃ©ssica => Jéssica
LetÃ­cia => Letícia
AndrÃ© => André

Wondering if there would be an upfront solution for this, or if we'd have to handle it on the output side.

thanks

**Comment by frdmn** [comment]
I created some test users and can not reproduce the issue.

The (UTF-8 encoded) CSV file is looking fine in plain text as well as in the CSV viewer (Numbers on macOS in my example screenshots):

<img width="1312" alt="bildschirmfoto 2018-04-07 um 02 00 25" src="https://user-images.githubusercontent.com/944459/38448784-789431b4-3a07-11e8-9819-0bf87d951692.png">

Which application did you use when you noticed the problem?

**Comment by andpiazza** [comment]
![image](https://user-images.githubusercontent.com/36119501/38448984-09f9e8bc-39cf-11e8-9923-7a96dcfee67b.png)

CSV export opened on MS-Excel for Windows

**Comment by andpiazza** [comment]
In fact, when I open the raw csv on notepad the characters are perfect.
So it is just Excel getting lost when importing the data... hmm

**Comment by andpiazza** [comment]
Yep - Gsheets imported CSV no problem. Thanks for looking into @frdmn !
