### ISSUE TITLE
sendUserListApiRequest(offset = 0)

### ISSUE THREAD

**Issue by ArchimedesFM** [frdmn/rocketchat-export-userlist#3]
Hello,

when I run _node export-userlist.js_ I get an error:

/root/rocketchat-export-userlist/export-userlist.js:31
function sendUserListApiRequest(offset = 0){
                                       ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

Whats wrong? What about the unexpected token? Is this the admin password as well?

With regards,
Lars

**Comment by frdmn** [comment]
Hey Lars, that's odd. Which version of Rocket.Chat are you using?

I'm going to see if I can reproduce the problem.

**Comment by ArchimedesFM** [comment]
0.69.2

**Comment by frdmn** [comment]
Can you try to update your Node version, looks like yours doesn't support initializing default paramters within functions.

**Comment by ArchimedesFM** [comment]
How do I update my node? The node version is 8.11.3
![image](https://user-images.githubusercontent.com/26709898/45626805-b1739880-ba90-11e8-84fd-b46726faa589.png)

**Comment by frdmn** [comment]
Can you run the following commands and give me the output?

```
$ node -v
$ npm -v
```

**Comment by ArchimedesFM** [comment]
node -v
v4.2.6
npm -v
3.5.2

I've installed nodejs-legacy and npm via apt-get install on Ubuntu 16.04.5 LTS.

**Comment by frdmn** [comment]
There's probably the root cause of the issue. Make sure to have at least Node 6 or newer installed and then try to run the script again :)

https://node.green/#ES2015-syntax-default-function-parameters

**Comment by ArchimedesFM** [comment]
Yes, you are absolutely right. It works very nice.
Thanks,
Lars

**Comment by frdmn** [comment]
Hey Lars,

sehe grade erst dass du ja auch deutsch sprichst. :)

Gerne - Bitte geb mir kurz Bescheid wenn du noch sonstige Verbesserungsvorschläge oder Probleme haben solltest.

Liebe Grüße,
Jonas
